[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Firebase service worker needs special headers
[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript" 